### ISSUE TITLE
CRITICAL __init__.py:70 - File /tmp/[...]/boot/vmlinuz* not found!

### ISSUE THREAD

**Issue by wintron04** [Elektrobit/ebcl_build_tools#14]
## Steps to reproduce
currently none found. Seems to happen sporadic. Will update as soon as smth is found.

[output.txt](https://github.com/user-attachments/files/17586487/output.txt)

**Comment by simone-weiss** [comment]
Workaround remove state.

**Comment by thir820** [comment]
Should be fixed with https://github.com/Elektrobit/ebcl_build_tools/blob/0ea7a584e943c0ec74a138730d71ea1e91322ccf/ebcl/common/proxy.py#L151
